export const REGISTER = "REGISTER"
export const FAIL = "FAIL"
export const LOGIN = "LOGIN"
export const CURRENT = "CURRENT"
export const LOGOUT = "LOGOUT"
export const GET_USERS ="GET_USERS"
export const GET_ONE_USER = "GET_ONE_USER"
